### ISSUE TITLE
关于使用上的一些问题

### ISSUE THREAD

**Issue by ChuanhongLi** [AlibabaPAI/llumnix#13]
非常赞的工作！有几个使用上的问题请教一下：
在一台物理机上（8张4090卡），我启动了一个容器，容器内可以使用这8张卡，如果使用vllm部署Qwen2-7B-Instruct实例，一个卡一个实例，我可以通过指定不同的端口来启动模型服务，比如 8001~8008，那么对应的我有8个模型服务；如果切换到 llumnix，作为我的调度器，这8个模型服务应该如何启动呢？

根据这里的描述，https://github.com/AlibabaPAI/llumnix/blob/main/docs/Quickstart.md
我启动单个模型实例没有问题：
```
CUDA_VISABLE_DEVICES=7 python -m llumnix.entrypoints.vllm.api_server \
                --host 0.0.0.0 \
                --port 8006 \
                --initial-instances 1 \
                --launch-ray-cluster \
                --model /models/QWen/Qwen2-7B-Instruct/ \
                --engine-use-ray \
                --worker-use-ray \
                --gpu-memory-utilization 0.8 \
                --max-model-len 10240
```
但是启动第二个实例时，即使我改动了  --port 的值，也无法拉起服务。请问这里应该如何操作？

第二个问题：通过 CUDA_VISABLE_DEVICES=7 指定模型服务运行到哪个卡上，貌似是无法生效？每次都是部署到了0号GPU上了，请问是无法指定卡吗? 

期待您的回复！谢谢

**Comment by s5u13b** [comment]
For first question, you should set 'HEAD_NODE_IP' and 'HEAD_NODE' environment variables correctly for launching ray cluster in Llumnix. You can provide us with the output to find the reason. Also, you can directly launch a '1 api server + 8 instances' service by setting 'initial-instances' to 8. For second question,

**Comment by s5u13b** [comment]
For first question, you should set `HEAD_NODE_IP` and `HEAD_NODE` environment variables correctly for launching ray cluster in Llumnix. You can provide us with the output to find the reason. Also, you can directly launch a '1 api server + 8 instances' service by setting `initial-instances` to 8. For second question, because Llumnix run command `ray start --head` in subprocess to launch ray cluster (see llumnix_utils.py), and CUDA_VISIBLE_DEVICES should be applied to `ray start --head` command. Therefore, the way that you used cannot take effects.

**Comment by ChuanhongLi** [comment]
> For first question, you should set `HEAD_NODE_IP` and `HEAD_NODE` environment variables correctly for launching ray cluster in Llumnix. You can provide us with the output to find the reason. Also, you can directly launch a '1 api server + 8 instances' service by setting `initial-instances` to 8. For second question, because Llumnix run command `ray start --head` in subprocess to launch ray cluster (see llumnix_utils.py), and CUDA_VISIBLE_DEVICES should be applied to `ray start --head` command. Therefore, the way that you used cannot take effects.

Thanks! When using vllm, if we want to deploy 4 model instances on the same  server with 4 cards, we can use the following command: 
```
CUDA_VISIBLE_DEVICES=0 python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-7B-Instruct-1 --model /models/QWen/Qwen2-7B-Instruct/ --port 8001
CUDA_VISIBLE_DEVICES=1 python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-7B-Instruct-2 --model /models/QWen/Qwen2-7B-Instruct/ --port 8002
CUDA_VISIBLE_DEVICES=2 python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-7B-Instruct-3 --model /models/QWen/Qwen2-7B-Instruct/ --port 8003
CUDA_VISIBLE_DEVICES=3 python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-7B-Instruct-4 --model /models/QWen/Qwen2-7B-Instruct/ --port 8004
```
and we can choose to access one of the model instance by IP+Port (http://localhost:$port/v1). 

When using llumnix, when we want to deploy 4 model instances on the same  server, we use the following command:
```
python -m llumnix.entrypoints.vllm.api_server \
                --host 0.0.0.0 \
                --port 8001 \
                --initial-instances 4 \
                --model /models/QWen/Qwen2-7B-Instruct/ \
                --engine-use-ray \
                --worker-use-ray \
                --gpu-memory-utilization 0.8 \
                --max-model-len 10240
```
that is to say, the IP+Port is the ip and port of the cluster(if the four model instance as the whole), and we can only access the model service by the cluster ip+port, and llumnix decides to diapatch the request to the specific model instance. Right?  Please correct me if i misunderstand something. 

Is there a url or something else can be used for us to choose which model instance to access, just like vllm case? 

Besides, if we want to deploy four model instance like vllm(CUDA_VISIBLE_DEVICES=0 python -m vllm.entrypoints.openai.api_server --served-model-name Qwen2-7B-Instruct-1 --model /models/QWen/Qwen2-7B-Instruct/ --port 8001) on the same server by llumnix, which command should we use? 

Thanks!

**Comment by s5u13b** [comment]
For the first question, yes. For the second question, to be more clear, I would like to first explain that Llumnix mainly aims for multi-instance deployment in k8s use case, which means that there is exactly 1 instance in 1 node. Base on this, Llumnix support launch ray cluster inside to automatically connect different nodes, and then serves for multiple instances. So launching multiple instances in 1 node is not Llumnix's typical use case. In current Llumnix(commit 0b48bbc), you can first set run `ray start --head` command first to set up ray cluster environment manually, and then launch multiple api servers just like the commands you gived above without passing `--launch_ray_cluster`. In this way, Llumnix can work correctly under your 'multiple instances in 1 node' use case. In the future, we will continue to improve our deployment methods to facilitate the users.

**Comment by ChuanhongLi** [comment]
Get it. Thanks for detailed reply！

**Comment by kobe24o** [comment]
vllm.yml

```
SERVER:
  HOST: "127.0.0.1"
  PORT: 1234
  REQUEST_OUTPUT_QUEUE_TYPE: "rayqueue"
  RAY_CLUSTER_PORT: 6379
  LAUNCH_RAY_CLUSTER: False

MANAGER:
  INITIAL_INSTANCES: 2
  DISPATCH_POLICY: 'load'
  ENABLE_MIGRATION: True
  ENABLE_SCALING: False

INSTANCE:
  DISPATCH_LOAD_METRIC: 'remaining_steps'
  MIGRATION_LOAD_METRIC: 'remaining_steps'

  ENABLE_DEFRAG: True
  MIGRATION_BACKEND: 'nccl'
  MIGRATION_BUFFER_BLOCKS: 512
  REQUEST_MIGRATION_POLICY: 'SR'
```
my start shell

```
export HEAD_NODE_IP='127.0.0.1'
export HEAD_NODE=1


CUDA_VISIBLE_DEVICES=2,3 ray start --head --port=6379 --dashboard-host=127.0.0.1 &

# launch prefill instance
python -m llumnix.entrypoints.vllm.serve --host 127.0.0.1 --port 8000 --model /models/ai2/llm/Qwen2.5-7B-Instruct/ --worker-use-ray --trust-remote-code --max-model-len 10240 --config-file vllm.yml \
--initial-instances 2 --max-model-len 10240 \
                --gpu-memory-utilization 0.8 \
                --max-num-seqs 10 \
                --max-num-batched-tokens 10240 --enable-port-increment  --enable-pd-disagg &
```

now test with curl, send openai format request
```
curl http://localhost:8000/v1/chat/completions     -H "Content-Type: application/json"     -d '{"model": "/models/ai2/Qwen2.5-7B-Instruct/","messages": [{"role": "user","content": "who are you ?"}],"max_tokens": 100,"temperature": 0, "stream": true}'
```
out : `{"detail":"Not Found"}`

is llumnix provide openai format api ?
