### ISSUE TITLE
一个论文疑问

### ISSUE THREAD

**Issue by wangyuwen1999** [AlibabaPAI/llumnix#2]
![image](https://github.com/user-attachments/assets/48d295ed-1f77-468a-b51b-9e1e7d2cc509)
请问，你们Fig 10左边的这幅图里面的blocking copy是否没有使用migration中的block fusion，以及并未使用live migration中的计算通信重叠操作。

**Comment by ZeldaHuang** [comment]
In blocking copy baseline:
1. We use block fusion in KV cache copying.
2. We do not overlap the migrating request's computation with KV cache copying.

**Comment by wangyuwen1999** [comment]
Do you mean the major part of block copying's overhead is the transfer time between two instances? How much percent of block fusion's overhead in the block copying's overhead?

**Comment by wangyuwen1999** [comment]
> In blocking copy baseline:
> 
> 1. We use block fusion in KV cache copying.
> 2. We do not overlap the migrating request's computation with KV cache copying.

Do you mean the major part of block copying's overhead is the transfer time between two instances? How much percent of block fusion's overhead in the block copying's overhead?

**Comment by ZeldaHuang** [comment]
> > In blocking copy baseline:
> > 
> > 1. We use block fusion in KV cache copying.
> > 2. We do not overlap the migrating request's computation with KV cache copying.
> 
> Do you mean the major part of block copying's overhead is the transfer time between two instances? How much percent of block fusion's overhead in the block copying's overhead?

Yes, the major part of block copying's overhead is the transfer time between instances, block fusion's overhead is quite small because H2D transfer (which use PCIe 4.0) is much faster than H2H transfer(which use network bandwidth).

**Comment by wangyuwen1999** [comment]
> > > In blocking copy baseline:
> > > 
> > > 1. We use block fusion in KV cache copying.
> > > 2. We do not overlap the migrating request's computation with KV cache copying.
> > 
> > 
> > Do you mean the major part of block copying's overhead is the transfer time between two instances? How much percent of block fusion's overhead in the block copying's overhead?
> 
> Yes, the major part of block copying's overhead is the transfer time between instances, block fusion's overhead is quite small because H2D transfer (which use PCIe 4.0) is much faster than H2H transfer(which use network bandwidth).

OK, I see. But why does the migration overhead seem to be constant for all seq len(even 8k seq len)? To my best knowledge, the overhead of block fusion will increase as the seq len increase.

**Comment by ZeldaHuang** [comment]
> OK, I see. But why does the migration overhead seem to be constant for all seq len(even 8k seq len)? To my best knowledge, the overhead of block fusion will increase as the seq len increase. Thanks for your reply!!!
During migration, we overlap the transfer with computation, the H2D/H2H run parallel with computation,

**Comment by ZeldaHuang** [comment]
> OK, I see. But why does the migration overhead seem to be constant for all seq len(even 8k seq len)? To my best knowledge, the overhead of block fusion will increase as the seq len increase. Thanks for your reply!!!

During live migration, the H2D/H2H transfer will overlap computation (except for the last stage),  the blocks number we transfer in last stage is near constant, so the the migration overhead is near constant.

**Comment by wangyuwen1999** [comment]
Sorry for asking so many questions, but I just want to find out the details of your experiment.

**Comment by ZeldaHuang** [comment]
> Sorry for asking so many questions, but I just want to find out the details of your experiment.

Feel free to ask questions. We use another cuda stream to do H2D transfer, so the H2D kernel and forward kernel will be overlapped (GIL will be released before calling cpp/cuda python bindings).

**Comment by wangyuwen1999** [comment]
> > Sorry for asking so many questions, but I just want to find out the details of your experiment.
> 
> Feel free to ask questions. We use another cuda stream to do H2D transfer, so the H2D kernel and forward kernel will be overlapped (GIL will be released before calling cpp/cuda python bindings).

since your code is pure python, and you use python package asyncio to maintain a thread (_update_instance_info_loop) to process the migration, I think your code do not release GIL(maybe I am wrong? please point out the code I miss.).  To my experiment, even you use different stream, the block fusion will not be overlap with computing. I list a result of my experiment which is maked by Nsight system.
![image](https://github.com/user-attachments/assets/0c96b884-58b5-4995-92ae-a52bc71214ca)
with my code:
![image](https://github.com/user-attachments/assets/edeb40bf-bdf5-496e-ae3f-9b2e9b761b8b)
In my code, cudamemcpyAsync and computeKernel is in different cudaStream.

**Comment by ZeldaHuang** [comment]
> > > Sorry for asking so many questions, but I just want to find out the details of your experiment.
> > 
> > 
> > Feel free to ask questions. We use another cuda stream to do H2D transfer, so the H2D kernel and forward kernel will be overlapped (GIL will be released before calling cpp/cuda python bindings).
> 
> since your code is pure python, and you use python package asyncio to maintain a thread (_update_instance_info_loop) to process the migration, I think your code do not release GIL(maybe I am wrong? please point out the code I miss.). To my experiment, even you use different stream, the block fusion will not be overlap with computing. I list a result of my experiment which is maked by Nsight system. ![image](https://private-user-images.githubusercontent.com/43462373/349107493-0c96b884-58b5-4995-92ae-a52bc71214ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDA5NjEsIm5iZiI6MTcyMTE0MDY2MSwicGF0aCI6Ii80MzQ2MjM3My8zNDkxMDc0OTMtMGM5NmI4ODQtNThiNS00OTk1LTkyYWUtYTUyYmM3MTIxNGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0Mzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiMjdkOTI5MmU0OWI5Yjg3ZDZlZjI4MWEyNWU2NThkYjI2NmQ3MzkwOWI2ODA0ZWJjZDRkZjBhMDYyZjA0ZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bAmWh7swdBBtcKjHCSpbUGLkQ2RhDZ0xH4PI7ic_gjw) with my code: ![image](https://private-user-images.githubusercontent.com/43462373/349108017-edeb40bf-bdf5-496e-ae3f-9b2e9b761b8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExNDA5NjEsIm5iZiI6MTcyMTE0MDY2MSwicGF0aCI6Ii80MzQ2MjM3My8zNDkxMDgwMTctZWRlYjQwYmYtYmRmNS00OTZlLWFlM2YtOWIyZTliNzYxYjhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDE0Mzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjMmNlYmM2NDFjNjI5M2JmNjJkMTMxNTk2NjY5MTcxYmM2ODhmMjBiNzhlZDhmNjFmNjZlNzQ1Yzg1MDI4NDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R-2Ou7voKkJaI8GxVjTtkGEUHg1F99-Us0rDgIGvLtA) In my code, cudamemcpyAsync and computeKernel is in different cudaStream.

It seems that you are not use pinned memory, you can try example in https://developer.nvidia.com/blog/how-overlap-data-transfers-cuda-cc/ . The release GIL opeartion is done in pytorch lib.

**Comment by wangyuwen1999** [comment]
> It seems that you are not use pinned memory, you can try example in https://developer.nvidia.com/blog/how-overlap-data-transfers-cuda-cc/ . The release GIL opeartion is done in pytorch lib.
emmm, my cudamemcpyAsync is a device-to-device copy，which means I do not need to use pinned memory. And I also change my code to device-to-host copy with pinned memory. I get a Nsight system fig:
![image](https://github.com/user-attachments/assets/942b515e-7c92-4f1c-a801-b0b5bbec002d)
Yes, we will get some overlap, but not all of them, since the data for transfer is so small

**Comment by ZeldaHuang** [comment]
Hi Yuwen, I'm not clear about your experiment, in our experiment the memcpy kernel is overlapped with compute kernel:
![image](https://github.com/user-attachments/assets/2bc7562d-831e-422a-a01d-654bd9346aff)

**Comment by wangyuwen1999** [comment]
> Hi Yuwen, I'm not clear about your experiment, in our experiment the memcpy kernel is overlapped with compute kernel: ![image](https://private-user-images.githubusercontent.com/48115868/349370852-2bc7562d-831e-422a-a01d-654bd9346aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDA3NDksIm5iZiI6MTcyMTIwMDQ0OSwicGF0aCI6Ii80ODExNTg2OC8zNDkzNzA4NTItMmJjNzU2MmQtODMxZS00MjJhLWEwMWQtNjU0YmQ5MzQ2YWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA3MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NmY2YTQxNTJmYjAxNWVkNDY3MDk0MjA2NDk1ZThiYzYxMjZmNzA1MGVmYWQyN2U4Mjc5ZjBhZTMwNTFiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14H0SPoIxUmmQV2D6l7NeLi7ppklR3q2E1Xo4zvr49I)

OK, now I know why. If you use RayWorker Thread, GIL does not constrain it， and you can totally overlap with compute.

**Comment by llx-08** [comment]
> > Hi Yuwen, I'm not clear about your experiment, in our experiment the memcpy kernel is overlapped with compute kernel: ![image](https://private-user-images.githubusercontent.com/48115868/349370852-2bc7562d-831e-422a-a01d-654bd9346aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDA3NDksIm5iZiI6MTcyMTIwMDQ0OSwicGF0aCI6Ii80ODExNTg2OC8zNDkzNzA4NTItMmJjNzU2MmQtODMxZS00MjJhLWEwMWQtNjU0YmQ5MzQ2YWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA3MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NmY2YTQxNTJmYjAxNWVkNDY3MDk0MjA2NDk1ZThiYzYxMjZmNzA1MGVmYWQyN2U4Mjc5ZjBhZTMwNTFiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14H0SPoIxUmmQV2D6l7NeLi7ppklR3q2E1Xo4zvr49I)
> 
> OK, now I know why. If you use RayWorker Thread, GIL does not constrain it， and you can totally overlap with compute.

Hi, I'm curious how you get that conclusion. Could you share the code for your experiments involving small and large overlaps?

**Comment by wangyuwen1999** [comment]
> > > Hi Yuwen, I'm not clear about your experiment, in our experiment the memcpy kernel is overlapped with compute kernel: ![image](https://private-user-images.githubusercontent.com/48115868/349370852-2bc7562d-831e-422a-a01d-654bd9346aff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMDA3NDksIm5iZiI6MTcyMTIwMDQ0OSwicGF0aCI6Ii80ODExNTg2OC8zNDkzNzA4NTItMmJjNzU2MmQtODMxZS00MjJhLWEwMWQtNjU0YmQ5MzQ2YWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE3VDA3MTQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NmY2YTQxNTJmYjAxNWVkNDY3MDk0MjA2NDk1ZThiYzYxMjZmNzA1MGVmYWQyN2U4Mjc5ZjBhZTMwNTFiYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.14H0SPoIxUmmQV2D6l7NeLi7ppklR3q2E1Xo4zvr49I)
> > 
> > 
> > OK, now I know why. If you use RayWorker Thread, GIL does not constrain it， and you can totally overlap with compute.
> 
> Hi @wangyuwen1999, I'm curious how you get that conclusion. Could you share the code for your experiments involving small and large overlaps?

sorry, since we change our server, I lost some code. But the code is simple, you can just make a lot of cudamemcpyAsync before your kernel，and use nsight system to watch the GPU action. After that, you can try to use pthread in C to run cudamemcpyAsync and thread to run kernel，also use nsight system to watch the GPU action.
