### ISSUE TITLE
How to run the baseline scheduler over Llumnix

### ISSUE THREAD

**Issue by AKafakA** [AlibabaPAI/llumnix#44]
Hey guys,

Do you know if the two baseline scheduler round-robin and infass++ has been included in the benchmarking scripts? And is that possible I can reproduce the results shown in figure 11 in the paper?

Thanks

**Comment by s5u13b** [comment]
Yes, you can run round-robin through setting `--dispatch-policy=balanced` without passing `--enable-migration` and run infaas++ through setting `--dispatch-policy=load` without passing `--enable-migration`. You can reproduce the results following the instructions in `osdi24ae` branch.
