### ISSUE TITLE
A potential bug case

### ISSUE THREAD

**Issue by PanJason** [AlibabaPAI/llumnix#68]
https://github.com/AlibabaPAI/llumnix/blob/2135d8b41ec21607647b749388fb3eea31e3b216/llumnix/backends/vllm/llm_engine.py#L273
Here, the remote function is directly invoked for a remote ray class, but the `remote()` call does not guarantee ordering, so we can possibly get reordered results from the client side.

**Comment by s5u13b** [comment]
According to the ray documents ([link](https://docs.ray.io/en/latest/ray-core/actors/task-orders.html)), 

> For tasks received from the same submitter, a synchronous, single-threaded actor executes them following the submission order.

However, if the request is migrated from `instance-A` to `instance-B`, the execution ordering of the `step-n` token put by `instance-A` and the `step-n+1` token put by  `instance-B` could not be guaranteed theoretically， we will take it into consideration and fix it.
