### ISSUE TITLE
[Usage]: Where is the Auto-Scaling Mechanism Implemented in llumnix?

### ISSUE THREAD

**Issue by Felixllq** [AlibabaPAI/llumnix#82]
Hi,
I noticed that the scale_up function is only invoked during the initial setup of llumnix. However, I couldn’t locate the specific implementation of the auto-scaling mechanism in the code. Could someone help me identify where the auto-scaling logic is implemented? Perhaps I missed it.

**Comment by zhypku** [comment]
Currently, Llumnix works in an external auto-scaling mode that relies on an external controller to dynamically create and destroy Llumnix workers. Therefore, Llumnix only needs to handle the membership changes, not the auto-scaling policies (which is delegated to the external controller).

If you are interested in the auto-scaling policies described in our paper, you can refer to the artifact branch (osdi24ae), vllm/core/request_scheduler.py.
